FROM python:alpine

# Install dependencies
RUN apk add --no-cache gcc python3-dev musl-dev linux-headers

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Define which folder executables are.
ENV PATH="/app/.venv/bin:$PATH"

# Run the application.
CMD ["fastapi", "dev", "src/dundie_api/main.py", "--port", "8000", "--host", "0.0.0.0"]