FROM python:3-slim-bookworm

RUN groupadd app && useradd -g app app

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app

RUN uv sync --frozen --no-cache

ENV PATH="/app/.venv/bin:$PATH"
ENV UV_CACHE_DIR="/app/.cache/uv"
ENV UV_LINK_MODE=copy

RUN chown -R app:app /app
USER app

# Run the application.
CMD ["fastapi", "dev", "src/dundie_api/main.py", "--port", "8000", "--host", "0.0.0.0", "--reload"]