# Cria um dicionário vazio para armazenar configurações padrão da aplicação.
# É uma sessão/tabela de comandos
[default]

# Cria dentro do dicionário uma subchave chamada 'db', com isso
# é possível importar esses valores através do objeto de configurações
# criado em 'config.py'.
# O acesso é utilizando notação de ponto.
[default.db]
# URI para conexão do banco de dados.
uri = ""
# Argumentos de conexão extra para serem passados ao conectar com
# o banco de dados.
connect_args = {check_same_thread=false}
# Desabilita a impressão dos comandos SQL usados no terminal e nos logs.
echo = false

# Configurações de segurança da aplicação.
[default.security]
# A chave deve ser definida em .secrets.toml.
#SECRET_KEY = ""
# Tempo de expiração do token de alterar a senha.
RESET_TOKEN_EXPIRE_MINUTES = 10
# URL do frontend para alteração da senha.
PWD_RESET_URL = "https://www.dm.com/reset_password"

# Configurações de servidor de email.
[default.email]
# Define se está em debug mode ou não.
debug_mode = true
# Email remetente.
smtp_sender = "no-reply@dm.com"
# Hostname do servidor de emails SMTP.
smtp_server = "localhost"
# Porta do servidor de emails SMTP.
smtp_port = 1025

# Usuário e senha para realizar a autenticação no servidor de emails,
# essas configurações devem estar em '.secrets.toml' e não devem ser enviadas
# para o repositório.
smtp_user = "<replace in .secrets.toml>"
smtp_password = "<replace in .secrets.toml>"

# Chave de configurações do Redis
[default.redis]
# Nome do host.
host = "redis"
# Porta para conexão.
port = 6379
